name: usuario_inri
description: A new Flutter project.
publish_to: 'none'

version: 2.0.7+13

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  

  # Core y arquitectura
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.5
  provider: ^6.1.1

  # Networking
  dio: ^5.4.0
  http: ^1.1.0
  socket_io_client: ^2.0.1
  connectivity_plus: ^5.0.2

  # Persistencia y almacenamiento
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.2

  # Funcionalidades del dispositivo
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  android_alarm_manager_plus: ^4.0.7
  flutter_local_notifications: ^19.0.3

  # UI y visuales
  flutter_map: ^7.0.2
  webview_flutter: ^4.2.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  hexcolor: ^3.0.1

  # Utilidades y otros
  intl: ^0.19.0
  latlong2: ^0.9.0
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.webp   
    - assets/driver.webp   
    - assets/background_image.webp
    - assets/logo.webp
    - assets/car_b.webp
    - assets/tarifas.json

  fonts:
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf

    - family: Satisfy
      fonts:
        - asset: fonts/Satisfy-Regular.ttf

    - family: RobotoB
      fonts:
        - asset: fonts/Roboto-Bold.ttf
